global:
  scrape_interval: 10s

scrape_configs:

- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']

- job_name: grafana
  static_configs:
  - targets: ['grafana:3000']
        
- job_name: eventstore-exporter
  static_configs:
  - targets: ['host.docker.internal:9448']
